version: '3.8'

networks:
    my-network:
        driver: bridge

volumes:
    my-volume:
        driver: local

services:
    app:
        build:
            context: docker/php
        volumes:
            - .:/var/www/html
        ports: 
            - 8000:80
        networks:
            - my-network

    db:
        image: postgres:15.2-alpine
        volumes:
            - my-volume:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
        networks:
            - my-network

    adminer:
        image: adminer:4.8.1
        ports:
            - 8081:8080
        networks:
            - my-network
